services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "3000:3000"
    command: yarn run start:prod
    depends_on:
      - db
    networks:
      - webnet
  db:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  data:
networks:
  webnet:
